### ISSUE TITLE
Speed differences between this and Capybara

### ISSUE THREAD

**Issue by AdamBrodzinski** [stuart/tuco_tuco#23]
I'm new to the Elixir community and I was wondering if this is considerably faster than Capybara? I have a large test suite and was wondering if there would be a perf benefit from using Elixir for this.

**Comment by stuart** [comment]
I doubt that there would be a great speed difference as the time taken is mainly in the browser request/response cycles and waiting for javascript to complete. It may be interesting to get some benchmarks

**Comment by AdamBrodzinski** [comment]
Ah gotcha... I was hoping it would run 100 test in parallel :smile:  My current Capybara setup is just running one at a time.
